import type { FromSchema } from 'json-schema-to-ts';
import * as schemas from './schemas';

export type AddressDetailsMetadataParam = FromSchema<typeof schemas.AddressDetails.metadata>;
export type AddressDetailsResponse200 = FromSchema<typeof schemas.AddressDetails.response['200']>;
export type FeedbackStatusMetadataParam = FromSchema<typeof schemas.FeedbackStatus.metadata>;
export type FeedbackStatusResponse200 = FromSchema<typeof schemas.FeedbackStatus.response['200']>;
export type PlaceFlagMetadataParam = FromSchema<typeof schemas.PlaceFlag.metadata>;
export type PlaceFlagResponse200 = FromSchema<typeof schemas.PlaceFlag.response['200']>;
export type PlaceMatchMetadataParam = FromSchema<typeof schemas.PlaceMatch.metadata>;
export type PlaceMatchResponse200 = FromSchema<typeof schemas.PlaceMatch.response['200']>;
export type PlaceProposeEditMetadataParam = FromSchema<typeof schemas.PlaceProposeEdit.metadata>;
export type PlaceProposeEditResponse200 = FromSchema<typeof schemas.PlaceProposeEdit.response['200']>;
export type PlaceSearchMetadataParam = FromSchema<typeof schemas.PlaceSearch.metadata>;
export type PlaceSearchResponse200 = FromSchema<typeof schemas.PlaceSearch.response['200']>;
export type PlaceSelectMetadataParam = FromSchema<typeof schemas.PlaceSelect.metadata>;
export type PlaceSelectResponse200 = FromSchema<typeof schemas.PlaceSelect.response['200']>;
export type PlaceTipsMetadataParam = FromSchema<typeof schemas.PlaceTips.metadata>;
export type PlaceTipsResponse200 = FromSchema<typeof schemas.PlaceTips.response['200']>;
export type PlacesNearbyMetadataParam = FromSchema<typeof schemas.PlacesNearby.metadata>;
export type PlacesNearbyResponse200 = FromSchema<typeof schemas.PlacesNearby.response['200']>;
